### ISSUE TITLE
Can only get plain text without syntax highlighting or frame

### ISSUE THREAD

**Issue by lloydjatkinson** [expressive-code/expressive-code#56] opened 2023-09-11 21:27 UTC
Hi,

Not sure what I'm doing wrong but I can only get simple plain text code blocks. I've looked over a few repositories using expressive-code and can't see any differences. I'm also using Tailwind and Tailwind Typography.

```ts
import { defineConfig, sharpImageService } from 'astro/config';
import tailwind from '@astrojs/tailwind';
import mdx from '@astrojs/mdx';
import expressiveCode from 'astro-expressive-code';

import addClasses from 'rehype-add-classes';
import remarkMath from 'remark-math';
import rehypeMathJax from 'rehype-mathjax';
export default defineConfig({
    site: 'https://www.lloydatkinson.net/',
    integrations: [
        tailwind(),
        expressiveCode(),
        mdx({
            remarkPlugins: [
                [
                    remarkMath
                ]
            ],
        }),
        // other stuff removed for brevity
    ],
});
```

In my MDX:
```
```tsx
type Cube = {
    position: Vector3;
    color: Color;
    rotationSpeed: number;
};
```

Which simply results in:

![image](https://github.com/expressive-code/expressive-code/assets/5633938/7d355e7d-8130-4400-bffb-276aa8f543f2)

**Comment by hippotastic** [comment] 2023-09-12 11:06
Hello Lloyd! I tried to reproduce your issue but failed doing so.

I created a new project using `pnpm create astro`, selected the blog template, used `astro add` to add both tailwind and astro-expressive-code, manually ran `pnpm i remark-math`, re-ordered all entries in `astro.config.mjs` to match your config, and added your example snippet to the "Markdown Style Guide" post. Here's how it looks:

![image](https://github.com/expressive-code/expressive-code/assets/6137925/285caa87-b6a0-4538-a1ce-eb76b2f94f4f)

Could you please try to create a minimal reproduction on StackBlitz?

**Comment by hippotastic** [comment] 2023-09-12 11:10
Addendum: It also works for me after installing and adding `require('@tailwindcss/typography')` to the plugins array in `tailwind.config.cjs`, so Tailwind Typography also doesn't seem to be the cause of the issue you're encountering locally.

**Comment by lloydjatkinson** [comment] 2023-09-12 11:23
Thanks for taking a look, I'll try make a repro. Do you think .md or .mdx would make any difference?

**Comment by hippotastic** [comment] 2023-09-12 12:33
It shouldn’t make a difference, but it wouldn’t hurt to try both for sure!

**Comment by lloydjatkinson** [comment] 2023-09-12 14:50
Here is a reproduction: https://stackblitz.com/edit/github-rgyx2d-8umn2i?file=astro.config.ts

It seems as though setting any remark plugins will overwrite anything expressive-code sets up...

**Comment by hippotastic** [comment] 2023-09-12 16:19
Thank you for the reproduction, that was very helpful! It seems that you were on the right track with your question regarding differences between `.md` and `.mdx` files:

After successfully reproducing the issue by uncommenting the MDX integration option `remarkPlugins` in your example, you can get everything to work again by simply renaming your post from `1.mdx` to `1.md`. The issue only affects MDX files.

It seems that as soon as the MDX integration's `remarkPlugins` option is defined (even if it's just set to an empty array), the MDX plugin ignores all of the Astro-wide remark plugins that normally get picked up by it. Expressive Code registers an Astro-wide remark plugin and this plugin is basically then doing all the work. This remark plugin is the reason why Expressive Code requests to be placed before MDX in the integrations array.

You can solve your issue and get any remark plugins to work in both `.md` and `.mdx` files by moving the `remarkPlugins` option from the MDX integration level to the Astro-wide config level:

```diff
export default defineConfig({
+   // This works
+   markdown: {
+       remarkPlugins: [[remarkMath, {}]],
+   },
    integrations: [
        tailwind(),
        expressiveCode({
            theme: 'light-plus',
        }),
        mdx({
-           // This doesn't work
-           remarkPlugins: [[remarkMath]],
            rehypePlugins: [[rehypeMathJax]],
        }),
    ],
});
```

**Comment by hippotastic** [comment] 2023-09-12 16:27
I was just checking if this is a bug in the MDX integration, but apparently it's intended. The behavior is documented here: https://docs.astro.build/de/guides/integrations-guide/mdx/#extendmarkdownconfig

> MDX will extend [your project’s existing Markdown configuration](https://docs.astro.build/en/reference/configuration-reference/#markdown-options) by default. To override individual options, you can specify their equivalent in your MDX configuration.

There's even an example where the global `remarkPlugins` option gets overwritten by the MDX integration option. 😅

**Comment by lloydjatkinson** [comment] 2023-09-12 17:40
This is awesome! Thank you for taking a look. Do you suggest that all remark **and** rehype plugins be specified in `markdown` instead `mdx({})`? It seems strange that remark plugins might be listed in `markdown` whereas rehype plugins might be listed in `mdx({})` - or does it not really matter?

**Comment by hippotastic** [comment] 2023-09-12 17:58
Thanks for the clarification question! I only showed the smallest change necessary to get your repro case to work. Generally, I think both remark and rehype plugins should be specified at the global `markdown` level by default.

**Comment by hippotastic** [comment] 2023-09-12 21:54
Closing as it's not an issue in Expressive Code, but the MDX integration working as designed and documented.

**Closed by hippotastic** 2023-09-12 21:54 UTC

**Comment by lloydjatkinson** [comment] 2023-09-12 22:02
Thank you for taking a look!
